services:
  zookeeper:
    networks:
      - CoinScope
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOO_LOG4J_PROP: "WARN, CONSOLE"
    ports:
      - 2181:2181

  kafka:
    networks:
      - CoinScope
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=log4j.properties -Dlog4j.rootLogger=WARN,stdout -Dlog4j.logger.kafka=WARN -Dlog4j.logger.org.apache.kafka=WARN -Dlog4j.logger.kafka.controller=WARN -Dlog4j.logger.kafka.log=WARN -Dlog4j.logger.state.change.logger=WARN"
    depends_on:
      - zookeeper

  frontend:
    environment:
      KAFKAPATH: kafka
      STREAMPATH: streamingserver
    depends_on:
      - kafka
      - streamingserver
    build:
      context: frontend
    # image: mohammadyehya/coinscope-frontend
    networks:
      - CoinScope
    ports:
      - 3000:3000

  streamingserver:
    environment:
      KAFKAPATH: kafka
    depends_on:
      - kafka
    build: 
      context: streamingserver
    # image: mohammadyehya/coinscope-streamingserver
    networks:
      - CoinScope
    ports:
      - 4000:4000

networks:
  CoinScope: