services:
  zookeeper:
    networks:
      - CoinScope
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    networks:
      - CoinScope
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  frontend:
    depends_on:
      - kafka
    build:
      context: frontend
    networks:
      - CoinScope
    ports:
      - 3000:3000

networks:
  CoinScope: